Extra check that expectation and javac agree.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -29,11 +29,17 @@ if true || test -t 1; then
    SUCCESS="[\e[32mSUCCESS\e[0m]"
    FAILURE="[\e[31mFAILURE\e[0m]"
    STUCK="[\e[34mSTUCK\e[0m]"
+   DISAGREE="[\e[34mDISAGREE\e[0m]"
 else
    SUCCESS="[SUCCESS]"
    FAILURE="[FAILURE]"
    STUCK="[STUCK]"
+   DISAGREE="[DISAGREE]"
 fi
+
+function expect {
+    if [ $1 -eq 0 ]; then printf "pass"; else printf "fail"; fi
+}
 
 function agree {
     [ $1 -eq 0 -a $2 -eq 0 ] || [ $1 -ne 0 -a $2 -ne 0 ]
@@ -44,24 +50,23 @@ do
     testname="${testfile%.java}"
     infiles="$(find "$testfile" -type f -name '*.java')"
 
-    if ! (echo "$testname" | grep -s ".no")
+    if ! (echo "$testname" | grep -s "\.no")
     then
         positive=0
-        echo "Expect pass"
     else
         positive=1
-        echo "Expect fail"
     fi
+    echo "Expect $(expect $positive)"
 
     ## Compile Java classes
     classes=$(mktemp -d -p . "${testname}.XXXXX.classes")
-    javac -d "$classes" $infiles 2>&1 | tee "${testname}.javac.out"
+    javac -d "$classes" $infiles 2>&1 | grep -v "Picked up JAVA_TOOL_OPTIONS" | tee "${testname}.javac.out"
     java_ok=${PIPESTATUS[0]}
     rm -rf "$classes"
-    if [ $java_ok -eq 0 ]; then
-        echo "JavaC pass"
-    else
-        echo "JavaC fail"
+    echo "JavaC $(expect $java_ok)"
+    if ! agree $java_ok $positive; then
+        printf "$DISAGREE $testfile\n"
+        continue
     fi
 
     ## Parse files to ATerm
@@ -90,16 +95,12 @@ do
     statix check -I $DIR/../src/ java "$testaterm" 2>&1 | tee "${testname}.stx.out"
     stx_ok=${PIPESTATUS[0]}
     rm -f "$testaterm"
-    if [ $stx_ok -eq 0 ]; then
-        echo "Statix pass"
-    else
-        echo "Statix fail"
-    fi
+    echo "Statix $(expect $stx_ok)"
 
     # compute test result by comparison
     if [ $stx_ok -eq 65 ]; then
         printf "$STUCK $testfile\n"
-    elif agree $stx_ok $java_ok && agree $java_ok $positive; then
+    elif agree $stx_ok $positive; then
         printf "$SUCCESS $testfile\n"
     else
         printf "$FAILURE $testfile\n"
